import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopNavbar from "@/components/desktopNavbar";
import Navbar from "@/components/navbar";
import NavabarContainer from "@/components/navabarContainer";
import AiChat from "@/components/AiChat";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
       <Providers>
        <NavabarContainer >
        <Navbar/>
       </NavabarContainer>
        {children}
        <AiChat />
       </Providers>
      </body>
    </html>
  );
}
